Models/Categorie.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCDemo.Models
{
    public class Categorie
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="The Name is required!"),MaxLength(20)]
        public string Name { get; set; }

        [Required(ErrorMessage = "The Creation Date is Required")]
        public DateTime CreationAt { get; set; }
        [Required(ErrorMessage = "The User Id is Required")]
        public string UserId { get; set; }
        //Navigation Property


        [ForeignKey("UserId")]
        public IdentityUser User { get; set; }
    }
}

Controllers/CategorieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCDemo.Data;
using MVCDemo.Dto_s;
using MVCDemo.Models;
using System;
using System.Diagnostics;
using System.Security.Claims;

namespace MVCDemo.Controllers
{
    [Authorize]
    public class CategorieController : Controller
    {
        private readonly ApplicationDbContext _context;
        

        public List<Categorie> list = new List<Categorie>();

        
        public string ErrorMessages {  get; set; }
        public string StatusMessages { get; set; }

        public Categorie Categorie = new Categorie();

        public CategorieController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var list = await _context.Categories
                    .Include(c=>c.User)
                    .Select(i=>new Categorie
                    {
                        Id=i.Id,
                        Name=i.Name,
                        CreationAt=i.CreationAt,
                        UserId=i.User.UserName
                    })
                    .ToListAsync();
                return View(list);
            }
            catch (Exception e)
            {
                Console.WriteLine("Date : " + DateTime.Now + ", Error on Get Category: " + e.Message);
                return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            }

        }
        [HttpGet]
        public async Task<IActionResult> AddEdit(int? id)
        {
            try
            {
                if (id != null && id>0)
                {
                    var categorie = await _context.Categories.FindAsync(id);
                    if (categorie==null)
                    {
                        return NotFound();
                    }
                    // Mapea la categoría a CategorieDto
                    var categorieDto = new CategorieDto
                    {
                        Id = categorie.Id,
                        Name = categorie.Name
                    };
                    return View(categorieDto);
                }
                return View(new CategorieDto());
            }
            catch (Exception e)
            {

                
                Console.WriteLine("Date: " + DateTime.Now + ", Error on Get Categorie: " + e.Message);
                return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier }); // Redirigir a la vista "Error"
            }

            return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier }); // Redirigir a la vista "Error"

        }
        [HttpPost]
        public async Task<IActionResult>AddEdit(CategorieDto model)
        {
            try
            {
                
                if (!ModelState.IsValid)
                {
                    foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                    {
                        Console.WriteLine($"Error: {error.ErrorMessage}");
                    }
                    Console.WriteLine("Model is InValid");
                    Console.WriteLine("Categorie : Id :" + model.Id + " Name :  " + model.Name );
                    return View(model);
                   

                }
                else
                {
                    Console.WriteLine("Model is valid");
                    // Obtén el ID del usuario actual
                    var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
                  Categorie categorie = new();
                    categorie.Id = model.Id;
                    categorie.Name = model.Name;
                    categorie.CreationAt= DateTime.SpecifyKind(DateTime.Now,DateTimeKind.Utc);
                    categorie.UserId = user;
                    // Asigna el ID del usuario actual al modelo
                  
                    Console.WriteLine("model.UserId : " + user);
                   
                    if (categorie.Id > 0)
                    {
                        _context.Categories.Update(categorie);
                        TempData["SuccessMessage"] = "Category has been update successfully.";
                    }
                    else
                    {
                        await _context.Categories.AddAsync(categorie);
                        TempData["SuccessMessage"] = "Category has been created successfully.";
                       
                    }

                    await _context.SaveChangesAsync();
                   
                    return RedirectToAction(nameof(Index));
                }
                
            }
            catch (Exception e)
            {

                ErrorMessages = e.Message;
                Console.WriteLine("Date : " + DateTime.Now + ", Error on Get Categorie : " + e.Message);
                return View(ErrorMessages);
            }
        }


        
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id!=null && id>0)
                {
                    var categorie = await _context.Categories.FindAsync(id);
                    if (categorie!=null)
                    {
                        var isInUsed = await _context.Products.AnyAsync(X => X.CategorieId == id);
                        if (isInUsed)
                        {
                            // Almacenar el mensaje de error en TempData
                            TempData["ErrorMessage"] = "This category is in use and cannot be deleted.";

                            // Redirigir al Index 
                            return RedirectToAction(nameof(Index));
                        }
                        
                        _context.Categories.Remove(categorie);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    // Almacenar el mensaje de error en TempData
                    TempData["ErrorMessage"] = "Category not Found! ";

                    // Redirigir al Index 
                    return RedirectToAction(nameof(Index));
                }
                // Almacenar el mensaje de error en TempData
                TempData["ErrorMessage"] = "This category Id is not Found!";

                // Redirigir al Index 
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {

                return View(e.Message);
            }

            return View("Internal Error");
        }
    }
}

Views/Categorie/AddEdit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model MVCDemo.Dto_s.CategorieDto
@{
 
}

<div class="row">
    <div class="col-md-6 mx-auto p-5">
        @if (Model.Id>0)
        {
            <h3 class="text-center text-primary">Edit Categorie</h3>
        }
        else
        {
            <h3 class="text-center text-primary">Create Categorie</h3>
        }

        <hr />
       
        <form asp-action="AddEdit">
        
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!-- Campo Id, oculto si no necesitas editar -->
            <input asp-for="Id" type="hidden"  />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

          
           
            <div class="form-group text-center pt-3">
                <!-- Si necesitas que el botón regrese, puedes usar un enlace -->
                <a href="@Url.Action("Index", "Categorie")" class="btn btn-success">Go Back</a>
                <button type="submit" class="btn btn-primary mx-5">Save</button>
            </div>
        </form>
    </div>
</div>

Views/Categorie/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model List<Categorie> 
@{
}
<div class="row">
    <div class="col-md-6 mx-auto 0">
        <h3 class="text-center text-success">List Of Categories  </h3>
        <hr />
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                @TempData["SuccessMessage"]
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }

        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                @TempData["ErrorMessage"]
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }

        @if (Model!=null)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Creation Date</th>
                        
                        <th scope="col">User</th>
                        <th scope="col">Options</th>
                        <th scope="col">
                            <a class="btn btn-outline-primary" asp-action="AddEdit">Create</a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.Name</th>
                            <td>@item.CreationAt</td>
                            <td>@item.UserId</td>
                            <td>
                                <a class="text-success" asp-action="AddEdit" asp-route-id="@item.Id"><i class="fa fa-marker fa-lg"></i></a> 
                                
                                <a class="text-danger" asp-action="Delete" asp-route-id="@item.Id"
                                onclick="return confirm('Are you sure dou you want delete this record?')"><i class="fa fa-trash-alt fa-lg"></i></a>
                            </td>
                        </tr>

                    }


                </tbody>
            </table>
        }
        else
        {
            <h3 class="text-info">Data not found</h3>
        }

    </div>
</div>